release:
  branches:
  - master
  - next
  repositoryUrl: https://github.com/gadicc/node-yahoo-finance2
  plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
